version: poco-{branch}-{build}

install:
  - cinst cmake

build_script:
  - set PATH=C:\Program Files\CMake\bin;C:\ProgramData\chocolatey\bin;%PATH%
  - cmake -H. -Bcmake-build -G"Visual Studio 14 2015 Win64"
  - cmake --build cmake-build
