version: poco-{branch}-{build}

install:
  - cinst cmake

build_script:
  - set PATH=C:\Program Files\CMake\bin;C:\ProgramData\chocolatey\bin;%PATH%
  - cmake -H. -Bcmake-build -G"Visual Studio 14 2015 Win64" -DODBC_ROOT_DIR="C:/Program Files/Microsoft SDKs/Windows/v7.0" -DENABLE_DATA_MYSQL=OFF
  - cmake --build cmake-build
